export const types = {
  SET_USER: 'SET_USER',
  SET_ROWS: 'SET_ROWS',
  SET_SCHEMA: 'SET_SCHEMA',
  SET_TABLES: 'SET_TABLES',
  SET_TABLE: 'SET_TABLE',
  SET_FIELDS: 'SET_FIELDS',
  SET_ROW_COUNT: 'SET_ROW_COUNT',
  SET_CURRENT: 'SET_CURRENT',
  SET_ORDER_BY: 'SET_ORDER_BY',
  SET_LIMIT: 'SET_LIMIT',
  SET_OFFSET: 'SET_OFFSET'
};
